# Generated by Django 5.1.7 on 2025-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_location_event_image_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/event_images/'),
        ),
    ]
